<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFrameworks>net10.0-android</TargetFrameworks>
      <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
      <OutputType>Exe</OutputType>
      <RootNamespace>DivisiBill</RootNamespace>
      <UseMaui>true</UseMaui>
      <SingleProject>true</SingleProject>
      <ImplicitUsings>disable</ImplicitUsings>
      <MauiStrictXamlCompilation>true</MauiStrictXamlCompilation>
      <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
	  <MauiXamlInflator>SourceGen</MauiXamlInflator>
	  <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies> <!--Because serialization assemblies do not play well with MAUI-->
     <LangVersion>preview</LangVersion> <!--In order to use partial properties via Community Toolkit-->
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <NoWarn>NU1608;CS1701</NoWarn>
     <!--NU1608 Because Xamarin.Android.Google.BillingClient triggers it on a bunch of Android dependencies-->
     <!--MVVMTK0045 because building tests triggers it and it's unnecessary-->
	 <!--CS1701 Because CommunityToolkit/Mvvm 8.4.0 is built against net prior to 10.0, causing this warning-->

	   <!-- Display name -->
      <ApplicationTitle>DivisiBill</ApplicationTitle>
 
      <!-- App Identifier -->
      <ApplicationId>com.autoplus.divisibill</ApplicationId>
      <ApplicationIdGuid>852FA570-F1CD-41BE-A828-5C1DE6ED088F</ApplicationIdGuid>
 
      <!-- Versions -->
      <ApplicationDisplayVersion>6.3.14</ApplicationDisplayVersion>
      <ApplicationVersion>300</ApplicationVersion>

      <ApplicationVersion Condition="'$(DIVISIBILL_VERSION_INCREMENT)' != ''">$([MSBuild]::Add($(ApplicationVersion), $(DIVISIBILL_VERSION_INCREMENT)))</ApplicationVersion>

      <AssemblyVersion>$(ApplicationDisplayVersion).$(ApplicationVersion)</AssemblyVersion>
 
      <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">34.0</SupportedOSPlatformVersion>
      <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
      <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
      <DefaultLanguage>en-us</DefaultLanguage>
      <Configurations>Debug;Release;ReleaseTest;Alternate</Configurations>
   </PropertyGroup>

	<!--Set EmitCompilerGeneratedFiles to true and CompilerGeneratedFilesOutputPath to an existing path to enable source-generated files to be visible in the IDE-->
	<PropertyGroup>
		<EmitCompilerGeneratedFiles Condition="'$(Configuration)'=='Debug'">false</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)GenDump</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<Target Name="DisplayCustomMessage" BeforeTargets="CopyFilesToOutputDirectory" Condition="'$(Configuration)'=='Debug'">
		<Message Text="$(MSBuildProjectName) $(Configuration) build for $(TargetFramework), Web Service URI = $(DivisiBillWsUri)" Importance="high" />
	</Target>

	<PropertyGroup>
     <!--Enables 'dotnet run' (along with "commandName": "Project" in launchsettings.json)-->
     <WindowsPackageType>None</WindowsPackageType>
   </PropertyGroup>

  <!--Turn on Android AOT compilation to Speed Up initialization-->
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
    <RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>

  <ItemGroup>
      <!-- App Icon, see https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005 -->
     <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android'" Update="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="Red" />
     <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="Red" />

     <!-- Splash Screen -->
      <MauiSplashScreen Include="Resources\Splash\appiconfg.svg" Color="Red" />

      <!-- Images -->
      <MauiImage Include="Resources\Images\*" />
      <MauiImage Update="Resources\Images\dotnet.svg" BaseSize="200,200" />

      <!-- Custom Fonts -->
      <MauiFont Include="Resources\Fonts\*" />

      <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
      <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
      <!-- Raw Web site Assets for DivisiBill with a "help" prefix to prevent name collisions with any other raw resources -->
      <MauiAsset Include="..\web\divisibill\**" LogicalName="help\%(RecursiveDir)%(Filename)%(Extension)" />
      <!-- Don't need the MD files -->
      <MauiAsset Remove="..\web\divisibill\**\*.md" />
   </ItemGroup>

   <ItemGroup>
     <MauiAsset Remove="Resources\Raw\md-template.html" />
     <MauiCss Remove="Resources\Raw\md-styles.css" />
     <MauiCss Remove="styles.css" />
   </ItemGroup>

   <ItemGroup>
     <None Remove="Resources\Images\dotnet.svg" />
     <None Remove="Resources\Splash\appiconfg.svg" />
   </ItemGroup>

   <ItemGroup>
     <MauiAsset Include="Release Notes.html" />
     <MauiAsset Include="styles.css" />
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
      <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
      <PackageReference Include="CommunityToolkit.Maui.Camera" Version="6.0.0" />
      <PackageReference Include="CommunityToolkit.Maui.Maps" Version="4.0.0" />
      <PackageReference Include="epj.RouteGenerator" Version="1.0.5" />
      <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.31" />
      <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.31" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.2" />
      <PackageReference Include="CommunityToolkit.Common" Version="8.4.0" />
      <PackageReference Include="CommunityToolkit.Maui" Version="14.0.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	  <PackageReference Include="Microsoft.Maui.Controls.Maps" Version="10.0.31" />
      <PackageReference Include="Sentry.Maui" Version="6.0.0" />
      <!--Sentry.Profiling 4.10.0 is not supported on Android-->
      <PackageReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android'" Include="Sentry.Profiling" Version="6.0.0" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
      <PackageReference Include="SkiaSharp" Version="3.119.2" />
   </ItemGroup>

	<!--Add In-App Billing package for Android-->
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="Xamarin.Android.Google.BillingClient" Version="8.1.0" />
  </ItemGroup>

  <!-- Sentry setup for PDB Upload -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(SENTRY_UPLOAD)' == 'true' and $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' and '$(DIVISIBILL_SENTRY_DSN)' != ''">

    <!-- Configure Sentry org and project -->
    <SentryOrg>autoplus</SentryOrg>
    <SentryProject>divisibill</SentryProject>

    <!-- Sends symbols to Sentry, enabling symbolic stack traces. -->
    <SentryUploadSymbols>true</SentryUploadSymbols>

  </PropertyGroup>

  <!--Make Sure DEBUG is set on Alternate builds-->
  <PropertyGroup Condition="$(Configuration) == alternate">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <!--Note that the following targets require Pandoc to be installed and available in the system PATH and are run by VS any time and dotnet CLI during the build process.-->
  <!-- markdown -> Release Notes html generation in-place; only runs when Release Notes.md is newer than html or html is missing -->
	<Target Name="GenerateReleaseNotesHtml" BeforeTargets="PrepareForBuild" Inputs="$(MSBuildProjectDirectory)\Release Notes.md" Outputs="$(MSBuildProjectDirectory)\Release Notes.html">
		<Exec Command="pandoc -o &quot;Release Notes.html&quot; &quot;Release Notes.md&quot; -s --template=pandoc-template.html --wrap=none" />
		<Message Text="Generating Release Notes.html from Release Notes.md" Importance="High" />
	</Target>

  <ItemGroup>
      <!-- DivisiBill Help MarkDown files: defined at project level so targets can use them for Inputs/Outputs -->
      <DivisiBillMarkdownFiles Include="..\web\divisibill\**\*.md" />
  </ItemGroup>

  <ItemGroup>
    <MauiAsset Include="script.js">
      <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </MauiAsset>
  </ItemGroup>

  <!-- help file markdown -> html generation in web\DivisiBill folder; only runs when .md is newer than html or html is missing -->
  <Target Name="GenerateDivisiBillHelpFile" BeforeTargets="PrepareForBuild" Inputs="@(DivisiBillMarkdownFiles)" Outputs="@(DivisiBillMarkdownFiles->'..\web\divisibill\%(RecursiveDir)%(Filename).html')">
      <Exec Command="pandoc -o &quot;..\web\divisibill\%(DivisiBillMarkdownFiles.RecursiveDir)%(DivisiBillMarkdownFiles.Filename).html&quot; &quot;%(DivisiBillMarkdownFiles.Identity)&quot; -s --template=pandoc-template.html --wrap=none" />
      <Message Text="Generating html file from %(DivisiBillMarkdownFiles.Identity)" Importance="High" />
  </Target>

  <!--Generate the file holding the build secrets on every build-->
  <!--First get the secrets from environment variables-->
  <PropertyGroup>
    <!--Set DivisiBillWsUri based on the build configuration-->
    <DivisiBillWsUri Condition="$(Configuration) == release">$(DIVISIBILL_WS_URI_RELEASE)</DivisiBillWsUri>
    <DivisiBillWsKey Condition="$(Configuration) == release">$(DIVISIBILL_WS_KEY_RELEASE)</DivisiBillWsKey>

    <DivisiBillWsUri Condition="$(Configuration) == alternate">$(DIVISIBILL_ALTERNATE_WS_URI)</DivisiBillWsUri>
    <DivisiBillWsKey Condition="$(Configuration) == alternate">$(DIVISIBILL_ALTERNATE_WS_KEY)</DivisiBillWsKey>
    <!--If it is not a build name we recognize just use the released configuration-->
    <DivisiBillWsUri Condition="'$(DivisiBillWsUri)' == ''">$(DIVISIBILL_WS_URI)</DivisiBillWsUri>
    <DivisiBillWsKey Condition="'$(DivisiBillWsKey)' == ''">$(DIVISIBILL_WS_KEY)</DivisiBillWsKey>
    <BuildInfoText>
<![CDATA[
// <auto-generated/>
// THIS FILE IS GENERATED BY EACH BUILD - DO NOT EDIT IT
namespace DivisiBill.Generated
{
    internal class BuildInfo
    {
        internal const string DivisiBillWsUri = "$(DivisiBillWsUri)"%3b
        internal const string DivisiBillWsKey = "$(DivisiBillWsKey)"%3b
        internal const string DivisiBillSentryDsn = "$(DIVISIBILL_SENTRY_DSN)"%3b
        internal const string DivisiBillTestProJsonB64 = "$(DIVISIBILL_TEST_PRO_JSON_B64)"%3b
        internal const string DivisiBillTestOcrJsonB64 = "$(DIVISIBILL_TEST_OCR_JSON_B64)"%3b
        internal const string DivisiBillTestProSignatureB64 = "$(DIVISIBILL_TEST_PRO_SIGNATURE_B64)"%3b
        internal const string DivisiBillTestOcrSignatureB64 = "$(DIVISIBILL_TEST_OCR_SIGNATURE_B64)"%3b
    }
}
]]>
    </BuildInfoText>
  </PropertyGroup>

  <Target Name="AddBuildInfo" Inputs="$(MSBuildAllProjects)" BeforeTargets="BeforeBuild;CoreCompile" Outputs="ForceBuildEveryTime">
    <Message Text="AddBuildInfo was invoked for file $(BuildInfoFilePath)" Importance="low" />
    <PropertyGroup>
      <BuildInfoFilePath>$(IntermediateOutputPath)BuildGenerated\BuildInfo.g.cs</BuildInfoFilePath>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include="$(BuildInfoFilePath)" />
      <FileWrites Include="$(BuildInfoFilePath)" />
    </ItemGroup>
    <WriteLinesToFile Lines="$(BuildInfoText)" File="$(BuildInfoFilePath)" Overwrite="true" />
  </Target>
  <!--End file generation-->

  <!--Generate the file holding the build timestamp, this changes on every build-->
  <PropertyGroup>
    <Today>$([System.DateTime]::UtcNow.ToString("O"))</Today>
    <BuildEnvironmentText>
<![CDATA[
// <auto-generated/>
// THIS FILE IS GENERATED BY EACH BUILD - DO NOT EDIT IT
namespace DivisiBill.Generated
{
    internal static class BuildEnvironment
    {
        internal const string BuildTimeString = "$(Today)"%3b
    }
}
]]>
    </BuildEnvironmentText>
  </PropertyGroup>

  <Target Name="AddBuildEnvironment" BeforeTargets="BeforeBuild;CoreCompile" Inputs="$(MSBuildAllProjects)" Outputs="ForceBuildEveryTime">
    <Message Text="AddBuildEnvironment was invoked for file $(BuildInfoFilePath)" Importance="low" />
    <PropertyGroup>
      <BuildEnvironmentFilePath>$(IntermediateOutputPath)BuildGenerated\BuildEnvironment.g.cs</BuildEnvironmentFilePath>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include="$(BuildEnvironmentFilePath)" />
      <FileWrites Include="$(BuildEnvironmentFilePath)" />
    </ItemGroup>
    <WriteLinesToFile Lines="$(BuildEnvironmentText)" File="$(BuildEnvironmentFilePath)" Overwrite="true" />
  </Target>
  <!--End file generation-->
</Project>
