<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>web</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- Display name -->
		<ApplicationTitle>web</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.autoplus.web</ApplicationId>

		<!--Simple packaging-->
		<WindowsPackageType>None</WindowsPackageType>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">28.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

		<!-- Raw Web site Assets for DivisiBill with a "help" prefix to prevent name collisions with any other raw resources -->
		<MauiAsset Include="divisibill\**" LogicalName="help\%(RecursiveDir)%(Filename)%(Extension)" />
		
		<!-- Don't need the MD files -->
		<MauiAsset Remove="divisibill\**\*.md" />
		
		<!-- Don't need the CSS file used for markdown preview -->
		<MauiAsset Remove="divisibill\md-styles.css" />

    <!--The release notes are in a different folder so we'll just use fake ones to go along with the other help files at run time-->
    <MauiAsset Include="Fake Notes.html" LogicalName="help\releasenotes.html" />
    <MauiAsset Update="Fake Notes.html">
      <DependentUpon>Fake Notes.md</DependentUpon>
    </MauiAsset>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
		<!--Show this as a folder in Solution Explorer even if it has no files.-->
		<Folder Include="Resources\Images\" />
	</ItemGroup>

  <ItemGroup>
    <MauiAsset Remove="divisibill\md-styles.css" />
  </ItemGroup>

  <ItemGroup>
	<!--This ItemGroup defines the layout of the help files which are usually in markdown format and are converted to HTML 
	for display in a WebView. The dependencies ensure that when a markdown file is updated, the corresponding HTML file is also
	recognized as needing an update.--> 

	<!-- DivisiBill HTML files with corresponding markdown dependencies -->
    <MauiAsset Update="divisibill\*.html">
      <DependentUpon>%(Filename).md</DependentUpon>
    </MauiAsset>

	<!--Also ensure that any images (SVG or PNG) that are used in the HTML files are also recognized as dependencies of the
	markdown files. This way, when you edit a markdown file, all related assets are correctly associated with it in the 
	project structure you see in the Solution Explorer.-->
	<!-- DivisiBill SVG files with corresponding markdown dependencies -->
	<MauiAsset Update="divisibill\*.svg">
		<DependentUpon>%(Filename).md</DependentUpon>
	</MauiAsset>
	<!-- DivisiBill PNG files with corresponding svg dependencies -->
	<MauiAsset Update="divisibill\*.png">
		<DependentUpon>%(Filename).svg</DependentUpon>
	</MauiAsset>

	<!-- AutoPlus HTML files with corresponding markdown dependencies -->
    <None Update="index.html">
      <DependentUpon>index.md</DependentUpon>
    </None>
    <None Update="policy.html">
      <DependentUpon>policy.md</DependentUpon>
    </None>
  </ItemGroup>
</Project>
